### PR TITLE
Mention types change in the upgrade guide

### LINKED ISSUE #1515: Upgrade guide fails to mention InjectedIntlProps is no longer available in v3
### Expected behavior

Expected `InjectedIntlProps` to remain.

### Current behavior

Errors everywhere. If I just remove that from the Props definition to get rid of that error, I get another:

image

### Step to reproduce for BUG REPORT

Upgrade to version 3.x

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | react-intl@3.6.0 |
|      `npm ls react` | react@16.11.0 |
|     `npm --version` | 6.13.0 |
|    `node --version` | v12.8.0 |

| OS   | Version |
| ---- | ------- |
| MacOS | 10.15.1 |

Other than saying that react-intl is now written in typescript, there are zero instructions on how to use it with typescript.

### PR DESCRIPTION
**Pull request by Zhouzi**
Although not a breaking change and outside of react-intl's reach, it'd be nice to inform developers about the new types. This PR adds a note about it. I'm not going into too much details as I understand that it's not the role of react-intl but just mention it.

Closes #1515

### CODE REVIEW

**Comment by longlho** [comment]
Thanks a lot for your contributions!

**Comment by longlho** [comment]
You'd wanna upgrade https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md instead :) and run `npm run toc && npm run format:fix` as well. Thanks!

**Comment by Zhouzi** [comment]
Damn sorry for completely messing up the first attempt 😣Should be good now 😀

**Comment by longlho** [comment]
Thanks a lot!

**Pull request merged**
