### PR TITLE
Fix performance issues on React Native Android

### PR DESCRIPTION
**Pull request by infostreams**

### CODE REVIEW

**Comment by infostreams** [comment]
This is a real issue on React Native / Android that has implications for the app as a whole. I understand that the original code was written to schedule as few updates as possible, most likely with the best possible performance in mind, but I don't think we should expect such a tiny component to have such big negative side effects?

**Comment by infostreams** [comment]
Can fix the tests but only if it's going to be merged 😬

**Comment by longlho** [comment]
I think this belongs in the documentation realm instead of actual code change since this issue is platform-specific. It'd be great if you can add this caveat to https://github.com/formatjs/react-intl/blob/master/docs/Components.md#formattedrelativetime

Thanks a lot for the contribution!

**Comment by infostreams** [comment]
Strong disagree that this is merely a documentation issue. Basically you cannot use the RelativeTime component on React Native, that's what this means.

**Comment by longlho** [comment]
You can if you set the interval to 30s+?

**Comment by infostreams** [comment]
Yes, as long as the interval is < 60 seconds it should work. See [thread here](https://github.com/facebook/react-native/issues/12981). There are ugly workarounds, obviously, but I think you should be able to use this library on React Native without workarounds.

**Comment by longlho** [comment]
Can you elaborate your use case? As I mentioned this is a platform-specific issue and introducing an arbitrary 30s minimum interval doesn't seem like the right solution.

1 other alternative is to turn off auto updating on this component and defer to the app level when the device wakes up.

cc @redonkulus

**Comment by infostreams** [comment]
Yes, my use case is that I'm displaying a news feed (in React Native) where I use a RelativeTime component to display something like '5 days ago' or 'just now'. The auto-updating feature for my use case is a 'nice to have', but not a must. I would be disappointed if it would have to be switched off because the code doesn't support React Native on Android.

The interval I suggested here is not a minimum interval but a maximum interval. If the interval is longer than 30 seconds, it will cut it off at 30 seconds (e.g. ```Math.min(30, 100000) == 30``` and ```Math.min(30, 2) == 2```) and then after 30 seconds check / renders again. I don't think I can conceive of a real world scenario in which this increased updating frequency would be very problematic. Would it?

**Comment by longlho** [comment]
It actually would yeah. The original idea behind only firing on "interesting" time mark is so we don't have performance spike at a regular interval. Yahoo does display an infinite news feed (so there can be a lot of these components mounted) and resource constraint becomes a real issue especially when there're ads involved.

Overall, I think this is a specific platform restriction and I don't see a whole lot of complaints surrounding this. Keep in mind that it'd hit the 30s threshold very quickly (basically right after the minute mark, since it'll schedule at minute interval afterwards). In terms of real world usage, for example, Dropbox considers everything under a minute old is `just now`, so it'll basically always hit this 30s threshold. Activity at the second interval isn't super actionable (from what I've seen, even in the Finance use case where seconds matter).

**Comment by infostreams** [comment]
Ok, I understand your use case. Could you live with adding platform specific code to resolve the issue and make this component work without warnings on React Native without having to resort to external workarounds?

**Comment by infostreams** [comment]
@longlho ?

**Comment by longlho** [comment]
Sorry unfortunately I won't merge this in.

**Comment by infostreams** [comment]
I just asked for a reply to my question, but it’s clear that you don’t care about this issue. I’ll fix this in my own repository with the excellent https://github.com/ds300/patch-package so you can ignore it for a bit until the next person opens the exact same ticket. Thanks.

**Pull request closed without merging**
