### PR TITLE
Fix #1158

### LINKED ISSUE #1158: Escaping curly braces does not work in production mode if the message has no format parameters
### Step to reproduce
Say you have a translations file that contains the following:
```JSON
{
  "example": "The string \\{token\\} is replaced with the actual token."
}
```

And you render this string in your React app like so:
```JS
props.intl.formatMessage({ id: "example" })
```

Then all is well in development mode and the string that gets inserted into the page is
```
The string {token} is replaced with the actual token.
```

However, once you run in production mode (`NODE_ENV === 'production'`), the string gets inserted with the backslash still present and the page renders as follows:
```
The string \{token\} is replaced with the actual token.
```

It looks like the root cause of this bug was introduced in the following commit:
https://github.com/yahoo/react-intl/commit/44168fb883f0419f0ddbbc3c154d127ca3d8c1f3. The relevant snippt is:
```JS
    if (!hasValues && process.env.NODE_ENV === 'production') {
        return message || defaultMessage || id;
    }
```
which skips formatting, which then means the correctly escaped curly is never unescaped.

| Executable | Version |
| ---: | :--- |
| react-intl | 2.4.0 |
| react | 16.4.1 |
| npm | 5.6.0 |
| node | v9.11.2 |

### PR DESCRIPTION
**Pull request by tranvansang**
To fix #1158 : curly braces are not escaped in production mode

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by BenLloydPearson** [comment]
Hello @tranvansang. Thank you very much for your contribution! Before we can accept it, we need you to take a few seconds to agree to our CLA at the link above.

**Comment by tranvansang** [comment]
@BenLloydPearson I did it already

```
Good to see you, Tran Van Sang
You previously signed this CLA on:
Tue Nov 13 2018 05:40:08 GMT+0000 (UTC)
From: 114.190.64.180
```

**Comment by redonkulus** [comment]
@tranvansang if this is still needed please make sure you have the latest from master. A unit test will also be needed. Otherwise, please close this PR. Thanks!

**Comment by tranvansang** [comment]
https://github.com/formatjs/react-intl/blob/master/src/format.ts#L300

I don't think that this is fixed

**Comment by longlho** [comment]
Can u add a test case & rebase off latest master please?

**Comment by tranvansang** [comment]
The fix is trivial. But I dont think I can arrange time to write test code.

Currently, I am patching the fix by [patch-package](https://www.npmjs.com/package/patch-package)

Should I close my PR?

**Comment by redonkulus** [comment]
Replaced by https://github.com/formatjs/react-intl/pull/1345

**Pull request closed without merging**
