### PR TITLE
Upgrade intl-messageformat & intl-relativeformat to 3

### PR DESCRIPTION
**Pull request by longlho**
smaller size but assume `Intl.PluralRules` polyfill

### CODE REVIEW

**Comment by longlho** [comment]
yeah I'm rebundling intl-pluralrules with intl-messageformat per https://github.com/formatjs/formatjs/pull/33

**Comment by longlho** [comment]
I bundled `intl-pluralrules` in the dist as well since it's not supported on Safari. LMK if I should pull it out.

**Comment by jaulz** [comment]
I noticed that I had to explicitely install `intl-pluralrules` for a React Native app but as far as I understood from this PR `Intl.PluralRules` should be in the bundle? Any idea what went wrong on my side?

**Comment by longlho** [comment]
@jaulz 	you're not doing anything wrong. We removed `intl-pluralrules` from the bundle bc FF/Chrome has it & the upcoming version of Safari will have it as well. This reduces the bundle size of `react-intl` for people using modern browsers.

**Comment by jaulz** [comment]
@longlho okay, thanks for the info! 😊

**Comment by longlho** [comment]
@jaulz 	if u're using React Native, I'd highly recommend you using the intl variant as well https://github.com/formatjs/react-intl/blob/master/docs/Getting-Started.md#intl-in-react-native that way you might not need the polyfills

**Pull request merged**
