### PR TITLE
fix: add a parser for chunks emitted from formatHTMLMessage

### PR DESCRIPTION
**Pull request by mallchel**
related to: https://github.com/formatjs/react-intl/issues/1549

### CODE REVIEW

**Comment by longlho** [comment]
Thanks a lot for your contributions! Can you add a test also? We have existing mocking of `console.log` that you can mirror to check for warning messages

**Comment by mallchel** [comment]
Yes, I will fix it tomorrow

**Comment by mallchel** [comment]
@longlho We could avoid array in the output of the prepareIntlMessageFormatHtmlOutput.
like this: 
```ts
export const prepareIntlMessageFormatHtmlOutput = (
  chunks: (string | object)[]
): React.ReactElement => React.createElement(React.Fragment, null, ...chunks);
```

But then we will lose information about the number of chunks, although this may be unnecessary

**Comment by longlho** [comment]
hmm if you do that u'll still get key warnings right?

**Comment by mallchel** [comment]
> hmm if you do that u'll still get key warnings right?

No, it will work as in the FormattedMessage component. Without key warnings 
image

**Comment by longlho** [comment]
Ah yeah I forgot. Yup I like that!

**Comment by mallchel** [comment]
@longlho ok, i have changes on the local machine. Will be committed on returning home

**Comment by longlho** [comment]
Thanks a lot for your contributions!

**Pull request merged**
