### PR TITLE
feat: support textComponent="", fixes #1330

### LINKED ISSUE #1330: Support textComponent="" to render raw strings on web
See #987 and particularly https://github.com/formatjs/react-intl/issues/987#issuecomment-503554085 and subsequent comments. We can avoid allocating an additional React.Fragment if the user specifically chooses the empty string (or perhaps `"string"` or `String`?) as the `textComponent`.

### PR DESCRIPTION
**Pull request by longlho**

### CODE REVIEW

**Comment by mvestergaard** [comment]
This change seems to be causing warnings about missing key when using rich content in message values. Specifically this change appears to be the cause https://github.com/formatjs/react-intl/pull/1354/files#diff-02d37c347364c13c106d74a9319ab545R157
There was a comment there that explains that this type of issue would happen when not using `React.createElement`. It should probably be changed back to that approach?

**Comment by longlho** [comment]
@mvestergaard 	would u mind creating a GH issue?

**Comment by ipanasenko** [comment]
I think you forgot to update types. TypeScript doesn't allow to set `textComponent=""` on `IntlProvider`

**Comment by DragonRaider5** [comment]
Hahaha the comment even was left untouched :D

**Pull request merged**
