### PR TITLE
Check code format before testing

### PR DESCRIPTION
**Pull request by okuryu**
It makes scripts `format` to check format, `format:fix` to fix format.

address: https://github.com/formatjs/react-intl/pull/1298#pullrequestreview-245433941
fixes: https://github.com/formatjs/react-intl/issues/1299

### CODE REVIEW

**Comment by okuryu** [comment]
hmm, weird.. 🤔 It passed tests in my box.

**Comment by redonkulus** [comment]
It passed on your box even before you formatted it?

**Comment by okuryu** [comment]
Gotcha, the `src/en.js` is a generated file. It should ignore `src/en.js`.

**Comment by okuryu** [comment]
OK, passed.

BTW, Yahoo CLA Bot is dead?

**Pull request merged**
