### PR TITLE
#1269 - contextTypes overriding

### LINKED ISSUE #1269: contextType of injectIntl is overridden by child component contextType
### Expected behavior
`contextType` of react-intl should not be overridden

### Current behavior
`contextType` of react-intl is overridden by child component's `contextType` field. The reason is that: react-intl uses an old version (2.5.5) of `hoist-non-react-statics` which doesn't include the new `contextType` field in the statics blacklist.

Updating the dependency to the latest version should fix the problem!

### Step to reproduce for BUG REPORT
1. Add own context to a react component using `Component.contextType = Context` or inside a class with babel `static contextType = Context;`
2. Wrapp `injectIntl` around the component

See live example: https://codesandbox.io/s/yv1q6xq66x

### Your Environment

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.8.0 |
| `npm ls react` | 16.8.6 |

| OS | Version |
| --- | --- |
| Arch Linux | 5.0.9 |

| Browser | Version |
| --- | --- |
| Chrome | 73.0.3683.103 |

### PR DESCRIPTION
**Pull request by tybenz**
Upgrades a dep to avoid the context override issue in #1269

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by tybenz** [comment]
@DragonRaider5 @ericf ... Can we get a maintainer to look at this PR? This is a blocking issue for my team & a really simple change.

**Comment by redonkulus** [comment]
@tybenz are you using version 3 now or do you need this for v2 branch?

**Comment by papasmile** [comment]
We have three of that same PR.... I think #1221 was first but has a conflict.

Also package-lock.json was removed in 3.0.0-beta but shouldn't it be added to `.gitignore`?

**Comment by redonkulus** [comment]
@papasmile I think the package-lock.json should be added once we move back to npm.

**Comment by tybenz** [comment]
@papasmile need it for v2. should i put up a separate PR?

**Comment by redonkulus** [comment]
@tybenz Yup, keep this one open, as we can upgrade v3 as well. You can open another PR against the [2.x branch](https://github.com/formatjs/react-intl/tree/2.x).

**Comment by tybenz** [comment]
@redonkulus ok updated this PR and opened one for 2.x

**Comment by redonkulus** [comment]
Released in v3.0.0-beta-2

**Pull request merged**
