### PR TITLE
feat: Use React.Fragment as default textComponent

### LINKED ISSUE #1262: FormattedMessage tagName propTypes should accept React.Fragment
It's possibe to use FormattedMessage with a React.Fragment tagName if we want to avoid the extra span, but it generates a propTypes warning while it's safe.

Workaround is:

`delete FormattedMessage.propTypes["tagName"];`

### PR DESCRIPTION
**Pull request by longlho**
- Fix some `any` casting
- Fix tests
- Closes #1262

### CODE REVIEW

**Comment by redonkulus** [comment]
FYI the convo from the open issue and linked issues https://github.com/formatjs/react-intl/issues/987

**Comment by longlho** [comment]
Yup I saw that one while going thru issues

**Comment by redonkulus** [comment]
It’s a large change for users. If we want to do this, we should mention how they can keep the span in the upgrade guide.

**Comment by longlho** [comment]
done

**Comment by slorber** [comment]
awesome :) please ping when there is a release

**Comment by DragonRaider5** [comment]
@longlho if we decide to do #1330, do you agree we should make this the default over `React.Fragment`?

**Comment by longlho** [comment]
yup

**Pull request merged**
